// 称号
export const medal = ['进步达人', '学习能手', '优秀标兵', '顶尖学霸', '完美学神'];

export const CustomerBaseInfo = {
	"code": "S200000",
	"message": "操作成功",
	"data": {
		"list": [{
			"customerId": 0,
			"clientSn": 0,
			"leadSn": 0,
			"brandId": null,
			"email": null,
			"countryArea": null,
			"mobile": null,
			"fname": "qatest",
			"lname": null,
			"englishName": null,
			"cname": "黎聪",
			"emailVerified": false,
			"birthday": null,
			"gender": 0,
			"headIcon": "https://s3cdn.tutorabc.com.cn/mem/vipabc/headIcon/d0f2e8756cf24289b7e5c7d6c46eeb4b.jpg",
			"headIconId": 0,
			"legalName": null,
			"spareEmail": null,
			"provinceId": null,
			"cityId": null,
			"regionId": null,
			"address": null,
			"idNo": null,
			"columbiaSn": 0,
			"companyId": 0,
			"serviceCode": null,
			"createdAt": "2018-10-10 17:44:02",
			"currentLevel": null,
			"englishLevel": null,
			"StudyDays": 731,
			"website": null,
			"currentUseTimeZone": null
		}],
		"totalCount": 1
	},
	"success": true
}

export const JRClientAnnualReview = {
	"Data": {
		"Items": [{
			"ClientSn": 479670,
			"LeadSn": 1399511,
			"ProBrandID": 4,
			"JRclientCNT": 270,
			"FirstAttendDate": "2016年3月21日",
			"FirstConSn": 18657,
			"FirstConName": "Aleksandar Bocic",
			"FirstSessionName": "Timmy's Adventures - Mexico",
			"TotalLong": 8845,
			"ClientRHCNT": 63,
			"AHCNT": 157,
			"AHScore": 17,
			"MostDiligentMonth": 3,
			"FavouriteConSn": 21404,
			"FavouriteConImage": "https://s3cdn.tutorabc.com.cn/con/adultPhoto/202008011125/674a7751-108b-479d-a97e-3d911049d8c7.jpg?1596252325?1",
			"FavouriteConName": "Thomas Dore",
			"FavouriteConAH": 1,
			"FavouriteConAttendDate": "/Date(1526486400000-0000)/",
			"FavouriteConSessionName": "Special Sessions: Essential Travel Conversations: Cruises",
			"ConCNT": 56,
			"NationalityCNT": 9,
			"CityCNT": 45,
			"ClassTimes": "20:30",
			"EvaluationCNT": 49,
			"HomeworkCNT": 151,
			"AVGScore": 0,
			"HomeworkScore": 0,
			"Classmates": 37,
			"Participation": 9,
			"Pronunciation": 8,
			"Comprehension": 9,
			"Creativity": 7,
			"Facility": 9,
			"Avgrating": 9.1,
			"RatingScore": 24,
			"olevel": 9,
			"nlevel": 9,
			"ClientTitle": "进步达人",
			"BeyondPercent": 86.7,
			"province": "上海市",
			"ModifiedBy": null,
			"CreatedBy": null,
			"ModifiedAt": "/Date(-62135596800000-0000)/",
			"CreatedAt": "/Date(-62135596800000-0000)/",
			"DxPage": 0,
			"DxPageSize": 0,
			"DxCacheExpiredTime": 0,
			"DxCacheProviderName": null,
			"DxExtension": {},
			"DxRefreshCache": false
		}],
		"TotalCount": 1,
		"DxDbQueryExecTime": null,
		"DxCacheKey": null,
		"DxCacheProviderName": null,
		"DxFromCache": false,
		"DxCacheTime": null,
		"DxSwitchedProvider": null,
		"DxExtension": {},
		"ClientIP": "192.168.20.80"
	},
	"ApiVersion": "4.0.30319.42000",
	"ExtendedDictionary": {},
	"Code": 1,
	"Msg": "",
	"ErrMsg": "",
	"IsSuccess": true,
	"SubCode": "",
	"SubMsg": ""
}

export const EventTrace = {
	"success": true,
	"code": "S200000",
	"message": "操作成功",
	"data": {
		"offset": 0,
		"limit": 10,
		"total": 226,
		"size": 10,
		"pages": 0,
		"current": 1,
		"searchCount": true,
		"openSort": true,
		"orderByField": null,
		"records": [],
		"condition": null,
		"asc": true,
		"offsetCurrent": 0
	}
}